#!/usr/bin/env ruby

require 'base64'
require_relative '../../lib/matasano'
require 'openssl'

file = Base64.decode64(ARGF.read)

puts Matasano.bytes_to_str(
  Matasano.decrypt_aes_128_cbc(
    Matasano.str_to_bytes(file),
    "YELLOW SUBMARINE"))
